# Simplismart config
SIMPLISMART_API_KEY = "ADD_SIMPLISMART_API_KEY_HERE"
SIMPLISMART_BASE_URL = "ADD_SIMPLISMART_DEPLOYED_CHAT_COMPLETIONS_ENDPOINT_HERE"
SIMPLISMART_MODEL_NAME = "meta-llama/Meta-Llama-3.1-8B-Instruct" 
ORG_ID = "ADD_ORG_ID_HERE"
MODEL_REPO_ID = "ADD_MODEL_REPO_ID_HERE"

# Fireworks config
FIREWORKS_API_KEY = "ADD_FIREWORKS_API_KEY_HERE"
FIREWORKS_BASE_URL = "ADD_FIREWORKS_DEPLOYED_CHAT_COMPLETIONS_ENDPOINT_HERE"
FIREWORKS_MODEL_NAME = "llama-v3p1-8b-instruct"

# Common benchmark config
NUM_RUNS = 5
REQUEST_TIMEOUT = 18
MAX_TOKENS = 100
TEMPERATURE = 0.2
